query ShuttleRealtimePageQuery(
    $language: String!
    $subwayLanguage: String!
    $after: LocalTime
    $weekday: String!
    $logDates: [Date!]
) {
    notices(input: {language: $language, category: "셔틀,날씨"}) {
        notices {
            title
            url
            expiredAt
        }
    },
    shuttle(input: {
        stops: [
            { name: "dormitory_o", limit: { order: 100, destination: 100 } },
            { name: "shuttlecock_o", limit: { order: 100, destination: 100 } },
            { name: "station", limit: { order: 100, destination: 100 } },
            { name: "terminal", limit: { order: 100, destination: 100 } },
            { name: "jungang_stn", limit: { order: 100, destination: 100 } },
            { name: "shuttlecock_i", limit: { order: 100, destination: 100 } },
        ],
        after: $after
    }) {
        initialStopRules {
            seq
            stopName
            priority
            polygon {
                latitude
                longitude
            }
        }
        stops {
            latitude
            longitude
            name
            timetable {
                order {
                    seq
                    route {
                        tag
                        name
                    }
                    time
                    stops {
                        stop
                        time
                    }
                }
                destination {
                    destination
                    entries {
                        seq
                        route {
                            tag
                            name
                        }
                        time
                        stops {
                            stop
                            time
                        }
                    }
                }
            }
        }
    }
    subway(input: { language: $subwayLanguage, keys: [
        { stationID: "K449", direction: ["up", "down"], weekdays: [$weekday], limit: 12 },
        { stationID: "K251", direction: ["up", "down"], weekdays: [$weekday], limit: 12 },
        { stationID: "K450", direction: ["up", "down"], weekdays: [$weekday], limit: 12 },
        { stationID: "K258", direction: ["down"], weekdays: [$weekday], limit: 12 },
        { stationID: "S26", direction: ["up"], weekdays: [$weekday] },
    ]}) {
        stationID
        arrival {
            direction
            entries {
                minutes
                isRealtime
                location
                stops
                terminal {
                    stationID
                    name
                }
            }
        }
        timetable {
            weekday
            direction
            time
            terminal {
                stationID
                name
            }
        }
    }
    transferBus: bus(input: [
        { route: 216000075, stop: 216000759, limit: 12, dates: $logDates },
        { route: 216000075, stop: 216000117, limit: 12, dates: $logDates },
    ]) {
        route {
            seq
            name
        }
        stop {
            seq
        }
        arrival {
            minutes
            stops
            isRealtime
        }
        log {
            date
            time
        }
    }
    alternativeBus: bus(input: [
        { route: 216000068, stop: 216000383, limit: 1 },
        { route: 216000068, stop: 216000379, limit: 1 },
        { route: 216000068, stop: 216000138, limit: 1 },
        { route: 216000081, stop: 216000028, limit: 1 },
        { route: 216000101, stop: 216000028, limit: 1 },
        { route: 216000016, stop: 216000152, limit: 1 },
        { route: 216000082, stop: 216000077, limit: 1 },
        { route: 216000102, stop: 216000077, limit: 1 },
        { route: 216000016, stop: 216000074, limit: 1 },
        { route: 216000082, stop: 217000140, limit: 1 },
        { route: 216000102, stop: 217000140, limit: 1 },
        { route: 216000016, stop: 217000264, limit: 1 },
    ]) {
        route { seq }
        stop { seq name latitude longitude }
        arrival { stops seats minutes lowFloor isRealtime time }
    }
}
